# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 301)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load106 = QtWidgets.QPushButton(self.centralwidget)
        self.load106.setGeometry(QtCore.QRect(10, 200, 75, 31))
        self.load106.setObjectName("load106")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 10, 491, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkManual = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkManual.setEnabled(True)
        self.checkManual.setStyleSheet("")
        self.checkManual.setObjectName("checkManual")
        self.horizontalLayout.addWidget(self.checkManual)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("background-color: rgb(229, 229, 229)")
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.checkStroki = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkStroki.setObjectName("checkStroki")
        self.horizontalLayout.addWidget(self.checkStroki)
        self.OKVED = QtWidgets.QPushButton(self.centralwidget)
        self.OKVED.setGeometry(QtCore.QRect(10, 10, 75, 71))
        self.OKVED.setObjectName("OKVED")
        self.dateStart = QtWidgets.QDateEdit(self.centralwidget)
        self.dateStart.setGeometry(QtCore.QRect(310, 50, 111, 31))
        self.dateStart.setStyleSheet("background-color: rgb(229, 229, 229)")
        self.dateStart.setReadOnly(True)
        self.dateStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 10, 12), QtCore.QTime(0, 0, 0)))
        self.dateStart.setDate(QtCore.QDate(2021, 10, 12))
        self.dateStart.setObjectName("dateStart")
        self.dateEnd = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEnd.setGeometry(QtCore.QRect(460, 50, 121, 31))
        self.dateEnd.setStyleSheet("background-color: rgb(229, 229, 229)")
        self.dateEnd.setReadOnly(True)
        self.dateEnd.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEnd.setObjectName("dateEnd")
        self.chekUpdate = QtWidgets.QCheckBox(self.centralwidget)
        self.chekUpdate.setEnabled(True)
        self.chekUpdate.setGeometry(QtCore.QRect(90, 60, 211, 17))
        self.chekUpdate.setIconSize(QtCore.QSize(1, 1))
        self.chekUpdate.setChecked(False)
        self.chekUpdate.setAutoRepeat(False)
        self.chekUpdate.setObjectName("chekUpdate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 50, 31, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 90, 271, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load106.setText(_translate("MainWindow", "106"))
        self.checkManual.setText(_translate("MainWindow", "Загрузка файлов вручную"))
        self.checkStroki.setText(_translate("MainWindow", "Ввод количества строк вручную"))
        self.OKVED.setText(_translate("MainWindow", "OKVED"))
        self.chekUpdate.setText(_translate("MainWindow", "Обновить данные ОКВЕД за период"))
        self.label.setText(_translate("MainWindow", "-"))
        self.pushButton.setText(_translate("MainWindow", "delete"))
