# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 301)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OKVED = QtWidgets.QPushButton(self.centralwidget)
        self.OKVED.setGeometry(QtCore.QRect(10, 10, 75, 31))
        self.OKVED.setObjectName("OKVED")
        self.load106 = QtWidgets.QPushButton(self.centralwidget)
        self.load106.setGeometry(QtCore.QRect(10, 40, 75, 31))
        self.load106.setObjectName("load106")
        self.RadioManualInput = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioManualInput.setGeometry(QtCore.QRect(100, 10, 161, 31))
        self.RadioManualInput.setObjectName("RadioManualInput")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 10, 104, 31))
        self.textEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("background-color: rgb(229, 229, 229)")
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OKVED.setText(_translate("MainWindow", "OKVED"))
        self.load106.setText(_translate("MainWindow", "106"))
        self.RadioManualInput.setText(_translate("MainWindow", "Загрузка файлов вручную"))
